//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaNaverMusic.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public int idAlbum { get; set; }
        public int Voto_DiarioAl { get; set; }
        public int Voto_SemanalAl { get; set; }
        public int Voto_MensualAl { get; set; }
        public int Votos_GeneralesAl { get; set; }
    }
}
