//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicaNaverMusic.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artista
    {
        public int idArtista { get; set; }
        public int Voto_DiarioAr { get; set; }
        public int Voto_SemanalAr { get; set; }
        public int Voto_MensualAr { get; set; }
        public int Votos_GeneralesAr { get; set; }
    }
}
